name: CI

on:
  pull_request:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

  push:
    branches: ["master", "main"]
    paths-ignore: ["docs/**"]

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" # Replace with the name of your GitHub Actions secret

      - uses: hashicorp/setup-terraform@v3

      - run: terraform init

      - run: ls

      - id: plan
        run: terraform plan -no-color

      - name: Apply
        run: terraform apply
